name: Release

on:
  workflow_dispatch:
  release:
    types: [ published, prereleased ]
    
permissions:
  contents: write
  packages: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Upload Release Assets
        uses: alexellis/upload-assets@0.4.0
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["Distribution/Fluent.rbxm", "Distribution/Fluent.lua"]'