name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of this release (e.g. v1.0)'
        required: true
        default: '1.0'
      summary:
        description: 'Summary of this release'
        required: true
        default: 'Initial release'
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.event.inputs.version }} --title "${{ github.event.inputs.version }}" --notes "${{ github.event.inputs.summary }}" --latest

  build-script:
    needs: ["create-release"]
    name: Bundle Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install Necessary Tools
        run: |
          rokit trust rojo-rbx/rojo
          rokit trust lune-org/lune
          rokit trust seaofvoices/darklua
          rokit install

      - name: Bundle
        run: lune run Build

      - name: Upload Minified Fluent to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ github.event.inputs.version }} "Distribution/Fluent.luau"

      - name: Upload Minified Fluent to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent.luau
          path: Distribution/Fluent.luau
      
      - name: Upload Fluent Model to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ github.event.inputs.version }} "Distribution/Fluent.rbxm"

      - name: Upload Fluent Model to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent.rbxm
          path: Distribution/Fluent.rbxm