name: Upload Release Assets

on:
  workflow_dispatch:
  release:
    types: [ published, prereleased ]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload Release Assets
        uses: alexellis/upload-assets@0.4.0
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["Distribution/Fluent.rbxm", "Distribution/Fluent.lua"]'

      - name: Remove Distribution folder
        run: rm -rf Distribution